### ISSUE TITLE
sc-list.txt is not loaded when auto config git-source-control

### ISSUE THREAD

**Issue by grongierisc** [intersystems/git-source-control#112]
When git-source-control is pre-install on a docker environment : 

```objectscript
 // Install source control
 zpm "install git-source-control"
 // Active it
 do ##class(%Studio.SourceControl.Interface).SourceControlClassSet("SourceControl.Git.Extension")
 // Configure it
 set ^SYS("SourceControl","Git","settings","mappings","CLS","*")	= 	"src/"
 set ^SYS("SourceControl","Git","settings","mappings","CLS","UnitTest")	= 	"test/"
 set ^SYS("SourceControl","Git","settings","mappings","INC","*")	= 	"inc/"
 set ^SYS("SourceControl","Git","settings","mappings","MAC","*")	= 	"rtn/"
 set ^SYS("SourceControl","Git","settings","namespaceTemp")	= 	"/irisdev/app/"
 set ^SYS("SourceControl","Git","settings","pullEventClass")	= 	"SourceControl.Git.PullEventHandler.Default"
 set ^SYS("SourceControl","Git","settings","ssh","privateKeyFile")	= 	""
 set ^SYS("SourceControl","Git","settings","user","irisowner","gitUserEmail")	= 	""
 set ^SYS("SourceControl","Git","settings","user","irisowner","gitUserName")	= 	""
```
it doesn't read sc-list.txt file on namespaceTemp to automatically add versioning on file present in sc-list.txt

sc-list.txt 
```
Connector.DT.HL7DefaultToFHIRBinary.cls
```

![image](https://user-images.githubusercontent.com/47849411/151025655-0a0edfef-3e7d-4aee-b1dd-3bc21041015e.png)

If I do it wrong, how can I do it right ?

**Comment by isc-svelury** [comment]
Can you try adding it by clicking the "Add" button? This should export the file out to the TempFolder based on the configured mappings, and run the `git add` command so that the file is properly tracked. 

The `sc-list.txt` file is used by the system to keep track of tracked files that are in IRIS and are tracked by Git. From what I can understand, it seems like you added files directly to `sc-list.txt`? If so, this won't add the file to source control. [This post](https://github.com/intersystems/git-source-control/discussions/90#discussioncomment-1746329) might shed some light on  how it all works.

**Comment by grongierisc** [comment]
Thanks, for pointing me to this issue : #90.

```objectscript
do ##class(SourceControl.Git.Utils).ImportSCList()
```

Helped git-source-control to take in consideration sc-list.txt.

In fact, It populate this global : 

```
 set ^SYS("SourceControl","Git","items","Connector.DT.HL7DefaultToFHIRBinary.cls") = ""
```
And solved my problem take in account sc-list.txt on docker build.

You can close the issue.

Thanks.

**Comment by grongierisc** [comment]
@isc-svelury thank for the advise, but I don't really use git-source-control for git ( I handle git with VsCode ), my use of git-source-control is just for extracting classes from the server side to my local folder then I can version them.
