### ISSUE TITLE
Track resources in the repo via global rather than sc-list.txt

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#120]
As part of this:
Import should be made package manager-aware.
Import in a non-package manager setting should just do a $System.OBJ.ImportAll() on all folders listed in the mappings global for various types.

@isc-svelury you've been in this code more than I have - do you see use cases for sc-list.txt that I'm missing (where we couldn't just track the list of files in a global)?

**Comment by isc-svelury** [comment]
I think `sc-list.txt` helps with consistent behavior across all the distributed repositories. What I mean by that is, if in one local repository, the user has added a new file to source control, this would be tracked by git and the global. When the user pushes their changes to the remote and a different local repository pulls these changes, the only way the new file would be added to the `^SYS("SourceControl", "Git", "items")` global right now would be through the corresponding changes to `sc-list.txt`. 

That being said, it is possible to do this update by looking at all the files git tracks (`git ls-tree --full-tree -r --name-only HEAD
`), getting their internal name and then updating the global. I don't think `sc-list` is used beyond that, and does feel clunky.

**Comment by CraigRegester** [comment]
"different local repository pulls these changes, the only way the new file would be added to the ^SYS("SourceControl", "Git", "items") global right now would be through the corresponding changes to sc-list.txt"

Wouldn't the solution here to be to adjust the 'pull' logic such that when that local pulls down a file/class they didn't previously 'track', it get added to the global then on ingestion ? I presume, since IRIS is fundamentally a trunk based development platform at its core imo, that the intent would always be for IRIS to ingest/compile anything it pulls in for this sort of solution.

**Comment by isc-tleavitt** [comment]
@CraigRegester yes, that's it. Generally: any time we import anything, we make sure it's in the global.

**Comment by isc-tleavitt** [comment]
@CraigRegester we can have discussions in issues too. :)

**Comment by isc-svelury** [comment]
Yes, an easier way than going through all the tracked files would be to just modify the behavior of pull to update the global. 

Also @isc-tleavitt currently we don't do any checks for new tracked files after pull. This will be fixed with this issue.
