### ISSUE TITLE
Error! Module 'set' not found

### ISSUE THREAD

**Issue by mander2211** [intersystems/git-source-control#137]
![image](https://user-images.githubusercontent.com/100713395/156215575-9e05d375-f7cb-4d90-90e0-ee2593fd64d5.png)

Getting a sql error on installing through ZPM.  Please see screenshot.  Thanks!

**Comment by mander2211** [comment]
using latest ZPM 0.3.2.  Won't install git-source-control

**Comment by isc-tleavitt** [comment]
I think disabling SQL statistics might help. See https://docs.intersystems.com/iris20212/csp/documatic/%25CSP.Documatic.cls?LIBRARY=%25SYS&CLASSNAME=%25SYSTEM.SQL.PTools#setSQLStatsFlag and https://docs.intersystems.com/iris20212/csp/docbook/Doc.View.cls?KEY=GSQLOPT_querytoolkit

**Comment by isc-tleavitt** [comment]
It would also be helpful if you were to run:
`zpm "install git-source-control -verbose"`
To see the context in which the error occurs.

**Comment by mander2211** [comment]
2021.2 is our IRIS version.  

I also tried running that line outside the shell, you can see in the screenshot it gave a syntax error.  possibly using the sql shell instead?

ill try disabling sql stats and using the verbose.  I really appreciate the help

**Comment by isc-tleavitt** [comment]
Oh... right, yeah, that's definitely not valid syntax! Looking at the class docs for that method (https://docs.intersystems.com/iris20212/csp/documatic/%25CSP.Documatic.cls?&LIBRARY=%25SYS&CLASSNAME=%25SYSTEM.SQL.PTools#getError) I think it's really saying:
```
do ##class(%SYS.PTools.Stats).getPToolsError(411,.errArray1)
do ##class(%SYS.PTools.Stats).getPToolsError(412,.errArray2)
```
Then look at the contents of the respective arrays. Although that's probably more of value to InterSystems Support in finding/fixing whatever error is happening in SQL stats!

Generally, that "ERROR #6084" thing comes up when something run by compilation produces an error %Status that isn't reported (in this case, probably the SQL stats, which is why turning them off should help). In this case I think it's probably an unreported error in SQL stats rather than an unreported error in git-source-control.

**Comment by mander2211** [comment]
Also verified through the portal.. but its still gathering stats.  Even restarted the IRIS service/instance.

![image](https://user-images.githubusercontent.com/100713395/157104581-28d21400-53ea-4971-a4f4-499c42b2c65a.png)
![image](https://user-images.githubusercontent.com/100713395/157104619-3f285b16-819c-4a7a-afd5-ef310b459d12.png)

**Comment by isc-tleavitt** [comment]
@mander2211 I'd recommend reaching out to InterSystems Support about this. https://www.intersystems.com/support-learning/support/

**Comment by isc-tleavitt** [comment]
@mander2211 was this ever sorted out?

**Comment by isc-tleavitt** [comment]
Going to assume this was covered through some other venue.
