### ISSUE TITLE
"Import All" doesn't pick up newly-added files

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#217]
It checks to see if they're in source control, which of course they aren't. (It just shouldn't check this.)

While investigating, also noted some issues operating in a package manager context. "Import All" and "Export All" should apply only to files in the current package context (or possibly the current lack thereof).

**Comment by a-schuetz** [comment]
Maybe instead of skipping the check you could add the new files to source control like this:

```Objectscript
#dim sc as %Status
if '..IsInSourceControl(internalName) {
    set sc = ..AddToServerSideSourceControl(internalName)
} else {
    set sc = ..ImportItem(internalName, force)
} 
```

Im not sure if this causes any unwanted behaviour. But for example if a checkout a remote branch wich contains new files and import it into IRIS, those files are already tracked by the Git repository, so it would make sense to also add them to the items in the global.

**Comment by isc-tleavitt** [comment]
@a-schuetz thanks for the comment. There are a few different paths where a new file could show up (including import) and really the global should be updated by any of them. I'm also not sure about possible unwanted behavior but will give that a try. Also, if you feel like digging around the code and submitting a PR you're always welcome - though this probably isn't a great introductory issue.

**Comment by a-schuetz** [comment]
I created a PR #218. I did test use cases that I had in mind and it works as I would expect it to. But maybe I didn't cover all use cases.
