### ISSUE TITLE
add support for system default settings

### ISSUE THREAD

**Issue by evshvarov** [intersystems/git-source-control#224]
<img width="831" alt="Screenshot 2023-01-15 at 3 41 47 PM" src="https://user-images.githubusercontent.com/2781759/212538547-d3a95bba-75a5-4d1f-9fe0-9a216ac6ac30.png">

**Comment by isc-tleavitt** [comment]
Two complications here:

1. System Default Settings aren't a %Studio.AbstractDocument, so we can't have source control hooks for them in the traditional sense.
2. System Default settings tend to inherently differ between environments (likely would need fancy git configuration if you have branch-per-environment)

That said, it's reasonable to think of automating best practices, taking those two things into account.

**Comment by evshvarov** [comment]
Sure.
But Interoperablity "System default settings" are the type of document,
here is an example of describing the resource:
https://github.com/intersystems-community/iris-interoperability-template/blob/ef3843dc1625868b4048098f5c3c31c753bc51fb/module.xml#L16

**Comment by isc-tleavitt** [comment]
@evshvarov I stand corrected!

There's one minor thing I lumped in to #222 that was breaking on ESD documents. Now you can map ESD in the Settings UI same as anything else, and work with them as .ESD documents in VSCode/Studio. The only question then as far as git-source-control is concerned is what an appropriate default mapping would be. (I'm inclined to not map by default, given typical use patterns.)

Another issue is that the management portal itself doesn't support source control hooks for system default settings. This is not something that can be fixed in git-source-control, and again I've reported it upstream (ref: DP-419914).

**Comment by isc-tleavitt** [comment]
With the minor fix from #222 (in 2.1.0), the remaining pieces of this issue are either upstream or covered in the clarified scope of #225 ; therefore, closing this issue.
