### ISSUE TITLE
Add support for IRIS BI

### ISSUE THREAD

**Issue by evshvarov** [intersystems/git-source-control#398]
Recommended solution:
Add a default mapping for the DFI extension

Original description from @evshvarov :
Currently, dashboards are being exported to an unexpected place - in class packages folders, rather than in /dfi/...

**Comment by isc-tleavitt** [comment]
@evshvarov what are your mapping configurations in the Settings page?

**Comment by isc-tleavitt** [comment]
ok - ultimately there just needs to be a default mapping for DFI among the initial/default mapping sets.

**Comment by isc-pbarton** [comment]
We should still add that default mapping, but I connected with Evgeny to see that this is an issue in an IPM package where the mappings should not be relevant.

Replicate by:
- install this package: https://github.com/intersystems-community/iris-analytics-template
- install git-source-control, and set it as the source control class for the namespace. Don't go through any additional configuration of git-source-control as it should not be necessary
- Edit the BI Dashboard. I see it exports to the /src folder instead of the /src/dfi folder

This might be just a configuration tweak required in the module.xml of that iris-analytics-template so git-source-control knows where to export the DFI.

**Comment by isc-tleavitt** [comment]
This is in fact an issue with module.xml - the resource(s) need Directory="dfi"; IPM is permissive about where it'll look for things to install/load and doesn't enforce a strict mapping.

**Comment by evshvarov** [comment]
@isc-tleavitt tried Directory="dfi" and didn't work from scratch.
Could you please suggest a PR to https://github.com/intersystems-community/iris-analytics-template/blob/master/module.xml ?

**Comment by isc-pbarton** [comment]
@evshvarov I made a PR here to add the Directory="dfi". The export was working for me once I reloaded the new module.xml.
https://github.com/intersystems-community/iris-analytics-template/pull/7

**Comment by evshvarov** [comment]
Thank you, @isc-pbarton ! Indeed this helped! 
It doesn't work for pivots though (as there is no git-source-control in Analyzer I guess).

**Comment by evshvarov** [comment]
I'll close this one anyway as this problem solved

**Comment by isc-pbarton** [comment]
I created a separate issue #428 to capture the improvement suggested in Tim's comment
