### ISSUE TITLE
How to import DFI not from /src/dfi folder

### ISSUE THREAD

**Issue by evshvarov** [intersystems/git-source-control#429]
If I don't use the Directory clause for DFI resources git-source-control exports to:

/src/folder/name.dashboard.xml

Consider the [following module.xml](https://github.com/intersystems-community/iris-analytics-template/blob/master/module.xml).
How can I describe resources so it can load/install DFI documents (pivots/dashboards) not from [/src/dfi/Covid19](https://github.com/intersystems-community/iris-analytics-template/tree/master/src/dfi/Covid19) folder but from /src/Covid19?

It looks like that now IPM ignores DFI documents if they are not in /src/dfi folder

**Comment by isc-tleavitt** [comment]
The original HS package manager was very prescriptive on the mapping of server document name to filename. IPM is less so for the sake of convenience, but it messes with source control a bit. (That is, it'll look for the same document in a few different possible places and load from wherever it's found.)

Bottom line, I'd expect the correct combination of Directory, FilenameTranslateAssociator, and FilenameTranslateIdentifier attributes on the .DFI resources to clear things up. Leaving this open to play with the sample use case a bit at some point when I have bandwidth.

**Comment by isc-tleavitt** [comment]
Finally got a chance to play with this here, and with latest everything it seems to "just work" with the folder structure you want:
https://github.com/isc-tleavitt/iris-analytics-template

One caveat: every time I rerun:
zpm "load /home/irisowner/irisdev -verbose"

It ends up reexporting all of the pivots/dashboards with a change to the lastAccessed property (which is a silly thing to source control). This looks like a new thing on 2024.1, because the load changes lastAccessed which then means the XML needs to be updated accordingly. This is despite the /diff qualifier used in $System.OBJ.ExportUDL.
