### ISSUE TITLE
v2.6.0 on IRIS 2022.1.3.668.0 Studio Git > Settings loads with error, and Git > Launch Git UI doesn't load at all

### ISSUE THREAD

**Issue by zdateh** [intersystems/git-source-control#604]
Following a troubled update that went through with some coaxing (see #603 ), I am now unable to load the various UI web page elements in Studio.

Git > Settings gives me this error:
![image](https://github.com/user-attachments/assets/ffa81351-fa81-45f1-805b-eb69910f70b4)
`'$' is undefined`
Behind the UI seems to load, but without full styling. The error repeats if you click on any buttons.

Git > Launch Git UI just hangs and doesn't load anything.

This is with Windows 10 + Edge Version 130.0.2849.56

**Comment by isc-tleavitt** [comment]
Offhand, I have no idea what would cause this. Usual suspects for this sort of error would be OS level file permissions on Linux, but you're on Windows, or filetype configuration for IIS, but you're on the private webserver. Given your comment in #603 that "the settings screens via Studio weren't loading" it seems that a configuration/other change prior to the installation of 2.6.0 could have broken things, and that they're still broken since.

Troubleshooting steps:
1. Try reinstalling with the "-verbose" flag and see if anything jumps out (and/or paste the logs)
`zpm "install git-source-control -verbose"`

2. Look for CSP-related issues happening under the hood. General process is to run the following one-liner in %SYS, then at the "read" request the page that's not doing what you want, and hit enter after it loads.
```
k ^ISCLOG s ^%ISCLOG = 3 read x s ^%ISCLOG = 0 zw ^ISCLOG
```
This is going to write out a LOT of text, most of which is useless, but there might be a smoking gun hiding somewhere in there.

3. Check / clear the web gateway cache - restarting the webserver is sufficient here.

If none of those steps fix or explain it I'm happy to have someone on my team hop on a call to debug; drop me an email: tleavitt at intersystems.com. (Also happy to have someone review logs if you'd rather not post them here.)

**Comment by isc-tleavitt** [comment]
It would also be good to have a listing of files under <install root>/devuser/studio/templates/gitsourcecontrol, and perhaps a check on the /isc/studio/usertemplates web application to make sure "Recurse" is checked.

**Comment by zdateh** [comment]
Thanks for the tips! A colleague has resolved this from those prompts, via the following, in case it helps:

> On zpm install log (attached), the extracted line below didn’t do anything:
> 
> ```
> Copying C:\InterSystems\IRISHealth\mgr\.modules\DEV_SL\git-source-control\2.5.0\git-webui\release\share\git-webui\webui\ to C:\InterSystems\IRISHealth\devuser\studio\templates\gitsourcecontrol\ as directory
> ```
> 
> Contents of the target folder:
> ![image](https://github.com/user-attachments/assets/6191b7c5-49c2-4f76-943e-9fbc59653178)
> 
> Copying the files manually, the folder now looks like this:
> ![image](https://github.com/user-attachments/assets/44eccfaf-5249-4cdc-8e2c-4410e7688b6a)
> 
> And our git settings in studio is back to normal

Not quite sure what to make of it - perhaps a permissions issue on our system? Presumably it's working for others!

**Comment by zdateh** [comment]
To answer the questions, as we seem to be getting a bunch of file related issues that are no doubt connected:

> Try reinstalling with the "-verbose" flag and see if anything jumps out (and/or paste the logs)
zpm "install git-source-control -verbose"

I have done this in https://github.com/intersystems/git-source-control/issues/673 - nothing seems to be obviously wrong, other than the mentioned Git issue (although I don't think we were getting that in v2.6.0 anyway)

> Look for CSP-related issues happening under the hood. General process is to run the following one-liner in %SYS, then at the "read" request the page that's not doing what you want, and hit enter after it loads.
> 
> Check / clear the web gateway cache - restarting the webserver is sufficient here.

I suppose this is redundant now that we know the csp files simply weren't being copied. If we copy the manually, it works, but given the copy issue is still occurring in v2.8.0 (we still have to manually copy the files as per https://github.com/intersystems/git-source-control/issues/604#issuecomment-2447357800), I will re-open this issue.

> It would also be good to have a listing of files under <install root>/devuser/studio/templates/gitsourcecontrol

The listing is above

> and perhaps a check on the /isc/studio/usertemplates web application to make sure "Recurse" is checked.

I am afraid I'm not sure how to get to this

I have sent you an email as I suspect this is clutter not useful to other users!

Thanks

**Comment by zdateh** [comment]
Following a call with @isc-etamarch I am happy to report this seems to be resolved! As suggested, it was probably a permissions issue that has since been resolved. Everything seems to working now! Thanks very much.
