### ISSUE TITLE
Updated git version requirement for git diff --diff-merges

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#62]
the --diff-merges option for git diff was added in git 2.31.0 (see https://git-scm.com/docs/git-diff/2.31.0 vs https://git-scm.com/docs/git-diff/2.30.0). I happened to be running an earlier version so the UI falls over now.

Two options:
* Detect version and avoid using the new flag on older versions
* Update documentation to say git 2.31.0+ is required

**Comment by isc-svelury** [comment]
git 2.31.0 was released on 15th March 2021. Is there any system that won't be able to run it? If we can be sure that a majority of systems won't have problems upgrading to it, then I think it makes sense to say git 2.3.1 is required. 

Otherwise we can detect the version and run a diff command if it is older. The other option is to just do a diff (which is what I was going to do initially) for merge commits.

**Comment by isc-tleavitt** [comment]
I agree, let's just say 2.31.0 is the minimum supported version. If we get pushback from users for some valid reason we can revisit.
